//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eNarudžba
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T34_DBEntities3 : DbContext
    {
        public T34_DBEntities3()
            : base("name=T34_DBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Hrana> Hrana { get; set; }
        public DbSet<HranaSastojci> HranaSastojci { get; set; }
        public DbSet<Korisnik> Korisnik { get; set; }
        public DbSet<Narudzba> Narudzba { get; set; }
        public DbSet<NarudzbaHrana> NarudzbaHrana { get; set; }
        public DbSet<NarudzbaPice> NarudzbaPice { get; set; }
        public DbSet<NarudzbaStatus> NarudzbaStatus { get; set; }
        public DbSet<Pice> Pice { get; set; }
        public DbSet<Placanje> Placanje { get; set; }
        public DbSet<PrivremenaTablica> PrivremenaTablica { get; set; }
        public DbSet<Sastojci> Sastojci { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TipKorisnika> TipKorisnika { get; set; }
        public DbSet<VelicinaHrane> VelicinaHrane { get; set; }
    }
}
